522 add fnn functionality
Safe-DS/Library pull request #529
Opened 2024-01-18 12:50 UTC by sibre28

Closes #522 

### Summary of Changes

Added Model and layer classes to support Feed Forward Neural Network Functionality.
Added into_dataloader() Function in TaggedTable Class, that creates a pytorch dataloader for any given tagged table, which can then be used to train a FNN.
Tests for those modules are probably incomplete, as i wasnt really sure what to test for, could use some feedback there.

2024-01-23 20:03 UTC, Marsmaennchen221 commented on src/safeds/ml/nn/_model.py
> +class PytorchModel(nn.Module):
This should only be an internal class, so consider using a leading underscore

2024-01-25 14:19 UTC, lars-reimann requested changes

2024-01-25 14:19 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +class ClassificationModel:
Use the [`Classifier`](https://library.safeds.com/en/stable/reference/safeds/ml/classical/classification/Classifier/#safeds.ml.classical.classification.Classifier) as the baseline for your interface.

2024-01-25 14:19 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +    def predict(self, test_data: TaggedTable) -> None:
Input must be a `Table`, it's not required to be a `TaggedTable`. The return value is a `TaggedTable`, not `None`.

2024-01-25 14:19 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +        accuracies_test = []
What is the purpose of computing loss values and accuracies in the `predict` method?

2024-01-25 14:19 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +    def is_for_regression(self) -> bool:
Seems out of place in a `ClassifierModel` class.

2024-01-25 14:19 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +class RegressionModel:
Name should clarify, that this is a neural network, not just any model.

2024-01-25 14:19 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +    def train(self, train_data: TaggedTable, epoch_size: int = 25, batch_size: int = 1) -> None:
The function must return the trained model and not `None`. The original model must not be mutated.

2024-01-25 14:19 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +    def train(self, train_data: TaggedTable, epoch_size: int = 25, batch_size: int = 1) -> None:
Try to be consistent with the other models. There, the function is called fit.

2024-01-25 14:19 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +class RegressionModel:
Use the [Regressor](https://library.safeds.com/en/stable/reference/safeds/ml/classical/regression/Regressor/) abstract class as the baseline for your interface.

2024-01-25 14:19 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +    def train(self, train_data: TaggedTable, epoch_size: int = 25, batch_size: int = 1) -> None:
The function must return the trained model and not None. The original model must not be mutated.

2024-01-25 14:19 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +        for _epoch in range(epoch_size):
Underscore not needed for local variable.

2024-01-25 14:19 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +    def predict(self, test_data: TaggedTable) -> None:
Input must be a Table, it's not required to be a TaggedTable. The return value is a TaggedTable, not None.

2024-01-30 16:15 UTC, sibre28 commented on src/safeds/ml/nn/_fnn_layer.py
> +    def get_pytorch_layer(self, is_for_classification: bool) -> _PytorchLayer:
Agreed, changed it to be a private method. The `is_for_classification` Flag is set in the init functions of ´RegressionModel` and `ClassificationModel` and is used to determine the activation function of a layer.

2024-02-09 11:04 UTC, Marsmaennchen221 commented on src/safeds/ml/nn/_model.py
> +            tmp_accuracies = []
Consider using a running loss/accuracy which is the current sum of the loss/accuracy in the epoch. You can get the average by dividing through the total number of batches*batch_size

2024-02-09 11:08 UTC, Marsmaennchen221 commented on src/safeds/ml/nn/_model.py
> +                optimizer.zero_grad()
Check whether this function is at the right position

2024-02-09 11:15 UTC, lars-reimann requested changes

2024-02-09 11:15 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +    def fit(self, train_data: TaggedTable, epoch_size: int = 25, batch_size: int = 1) -> Self:
* Add callback `on_epoch_completion` callback that gets called whenever an epoch is done.
* Add callback `on_batch_completion` callback that gets called whenever a batch is done.

2024-02-09 11:15 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +    def fit(self, train_data: TaggedTable, epoch_size: int = 25, batch_size: int = 1) -> Self:
Callbacks for epoch & batch completion.

2024-02-09 11:15 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +        accuracies = []
Accuracy does not make sense for a regression model. There's also no need to keep track of a single metric if the callback are available. -> Remove `accuracies` completley.

2024-02-09 11:15 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +        accuracies = []
There's also no need to keep track of a single metric if the callback are available. -> Remove `accuracies` completley.

2024-02-09 11:15 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +        return copied_model
Set the `eval` mode here before returning.

2024-02-09 11:15 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +        copied_model._is_fitted = True
Set `eval` mode here before returning.

2024-02-09 11:15 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +        copied_model = copy.deepcopy(self)
Copy should not be needed for prediction.

2024-02-09 11:15 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +        copied_model = copy.deepcopy(self)
Copy should not be needed for prediction.

2024-02-09 11:15 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +        copied_model._model.eval()
`eval` mode should already be set after fitting.

2024-02-09 11:15 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +        copied_model._model.eval()
`eval` mode should already be set after fitting.

2024-03-02 20:15 UTC, lars-reimann requested changes

2024-03-02 20:15 UTC, lars-reimann commented on src/safeds/data/tabular/containers/_table.py
> +        batch_size : int
```suggestion
        batch_size
```

Docstrings should no longer contain types.

2024-03-02 20:15 UTC, lars-reimann commented on src/safeds/data/tabular/containers/_table.py
> +        result : DataLoader
```suggestion
        result :
```

The colon is needed for results.

2024-03-02 20:15 UTC, lars-reimann commented on src/safeds/data/tabular/containers/_tagged_table.py
> +        batch_size : int
```suggestion
        batch_size
```

2024-03-02 20:15 UTC, lars-reimann commented on src/safeds/data/tabular/containers/_tagged_table.py
> +        result : DataLoader
```suggestion
        result :
```

2024-03-02 20:15 UTC, lars-reimann commented on src/safeds/ml/nn/_fnn_layer.py
> +        input_size : int
```suggestion
        input_size
```

2024-03-02 20:15 UTC, lars-reimann commented on src/safeds/ml/nn/_fnn_layer.py
> +        output_size : int
```suggestion
        output_size
```

2024-03-02 20:15 UTC, lars-reimann commented on src/safeds/ml/nn/_fnn_layer.py
> +        result: int
```suggestion
        result :
```

2024-03-02 20:15 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +            Function used to view metrics while training. Gets called after an epoch is completed.
```suggestion
        train_data
            The data the network should be trained on.
        epoch_size
            The number of times the training cycle should be done.
        batch_size
            The size of data batches that should be loaded at one time.
        callback_on_batch_completion
            Function used to view metrics while training. Gets called after a batch is completed.
        callback_on_epoch_completion
            Function used to view metrics while training. Gets called after an epoch is completed.
```

2024-03-02 20:15 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +        RegressionNeuralNetwork
```suggestion
        trained_model :
```

2024-03-02 20:15 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +        test_data : Table
```suggestion
        test_data
```

2024-03-02 20:15 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +        TaggedTable
```suggestion
        prediction :
```

2024-03-02 20:15 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +        is_fitted : bool
```suggestion
        is_fitted
```

2024-03-02 20:15 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +            The size of data batches that should be loaded at one time.
```suggestion
        train_data
            The data the network should be trained on.
        epoch_size
            The number of times the training cycle should be done
        batch_size
            The size of data batches that should be loaded at one time.
```

2024-03-02 20:15 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +        test_data : Table
```suggestion
        test_data
```

2024-03-02 20:15 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +        TaggedTable
```suggestion
        prediction :
```

2024-03-02 20:15 UTC, lars-reimann commented on src/safeds/ml/nn/_model.py
> +        is_fitted : bool
```suggestion
        is_fitted :
```

2024-03-06 12:37 UTC, Gerhardsa0 commented on src/safeds/data/tabular/containers/_table.py
> +    def into_dataloader(self, batch_size: int) -> DataLoader:
this should be a private function, as the user will not use this function and work directly on Torch objects.

```_into_dataloader``` or mby add something like a neural network utils

2024-03-20 16:15 UTC, lars-reimann approved these changes
We might need to make some adjustments later, but for now this is good to go.

2024-03-20 16:15 UTC, merged

2024-04-03 08:35 UTC, lars-reimann commented
:tada: This PR is included in version 0.20.0 :tada:

The release is available on:
- `v0.20.0`
- [GitHub release](https://github.com/Safe-DS/Library/releases/tag/v0.20.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: