perf: improved performance of `TabularDataset.__eq__` by a factor of up to 2
Safe-DS/Library pull request #697
Opened 2024-05-03 00:55 UTC by Marsmaennchen221

### Summary of Changes

perf: improved performance of `TabularDataset.__eq__` by a factor of up to 2
perf: slightly improved performance of `TabularDataset.__hash__`
fix: corrected `TabularDataset.__sizeof__`

2024-05-03 00:57 UTC, Marsmaennchen221 commented
@lars-reimann do you really want to save the exact same data twice in a `TabularDataset`? Wouldn't it be better to not save the whole table and compact `_features`, `_target` and `_extras` if the user uses the `TabularDataset.to_table` method?

2024-05-03 05:21 UTC, lars-reimann commented
Due to `pandas`'s copy-on-write semantics the current approach should barely need more memory. We only store some extra pointers.

We should add some performance benchmarks , though, to check runtime and memory use of the current implementation (not needed for this PR).

2024-05-03 05:38 UTC, lars-reimann commented
Regarding column order: Should that matter for equality? If so, we should compare the tables and the names of target, features, and extras.

2024-05-03 18:43 UTC, lars-reimann requested changes

2024-05-06 13:11 UTC, Marsmaennchen221 commented on src/safeds/data/labeled/containers/_tabular_dataset.py
> +            + sys.getsizeof(self._extras)
```suggestion
            sys.getsizeof(self._target)
            + sys.getsizeof(self._features)
            + sys.getsizeof(self._extras)
```

2024-05-06 14:17 UTC, lars-reimann approved these changes

2024-05-06 14:17 UTC, merged

2024-05-09 13:31 UTC, lars-reimann commented
:tada: This PR is included in version 0.24.0 :tada:

The release is available on:
- `v0.24.0`
- [GitHub release](https://github.com/Safe-DS/Library/releases/tag/v0.24.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: