521 feat add moving average plot 1
Safe-DS/Library pull request #836
Opened 2024-06-11 16:21 UTC by Gerhardsa0

Closes #XYZ

### Summary of Changes

added moving average plot

2024-06-11 17:13 UTC, Gerhardsa0 commented
Should there also be an moving average function for a Column, which calculates the moving average and returns it as a column.
The same goes for windows.

2024-06-20 14:25 UTC, sibre28 requested changes

2024-06-20 14:29 UTC, Gerhardsa0 commented on tests/safeds/data/tabular/plotting/test_moving_average_plot.py
> +    ids=["numerical", "date grouped", "date"],
the snapshot fails for some reason, but it is still the correct plot

2024-06-20 14:32 UTC, Gerhardsa0 commented on tests/safeds/data/tabular/plotting/test_moving_average_plot.py
> +def test_should_match_snapshot(
this would be non numerical data, for that the average is not defined and cant be plotted.
The plot is only for numerical data only

2024-06-20 15:06 UTC, Gerhardsa0 commented on src/safeds/data/tabular/plotting/_table_plotter.py
> +    def moving_average_plot(self, x_name: str, y_name: str, window_size: int) -> Image:
added

2024-06-20 15:15 UTC, sibre28 commented on tests/safeds/data/tabular/plotting/test_moving_average_plot.py
> +def test_should_match_snapshot(
Are we currently throwing an error if somebody tries this? Or is it even possible to call this Method with invalid data?

2024-06-20 15:24 UTC, Gerhardsa0 commented on tests/safeds/data/tabular/plotting/test_moving_average_plot.py
> +def test_should_match_snapshot(
to both, yes.
I didnt test it here explicitly, because it usees the _plot_validation function, which is covered in other tests.

2024-06-21 11:11 UTC, sibre28 approved these changes

2024-06-21 11:14 UTC, merged

2024-07-19 13:02 UTC, lars-reimann commented
:tada: This PR is included in version 0.27.0 :tada:

The release is available on:
- `v0.27.0`
- [GitHub release](https://github.com/Safe-DS/Library/releases/tag/v0.27.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: