prediction no longer takes a time series dataset only table
Safe-DS/Library pull request #838
Opened 2024-06-12 14:19 UTC by Gerhardsa0

Closes #XYZ

### Summary of Changes

Prediction no longer takes time series dataset.

2024-06-20 12:54 UTC, Gerhardsa0 commented
@lars-reimann allowing Dataset as type for predict would take a deeper impact to the interface, as the table interface and Image the image interface also need to allow dataset as type. Is this wanted?

2024-06-20 15:35 UTC, lars-reimann commented
Let's defer that change until later and only allow tables for now.

2024-06-25 18:54 UTC, Marsmaennchen221 requested changes

2024-06-25 18:54 UTC, Marsmaennchen221 commented on src/safeds/ml/nn/converters/_input_converter_time_series.py
> +        self._extra_names: list[str] = []
Add the `_extra names` in the `__eq__`, `__hash__` and `__sizeof__` methods

2024-06-29 18:40 UTC, Marsmaennchen221 approved these changes

2024-07-01 13:40 UTC, merged

2024-07-19 13:01 UTC, lars-reimann commented
:tada: This PR is included in version 0.27.0 :tada:

The release is available on:
- `v0.27.0`
- [GitHub release](https://github.com/Safe-DS/Library/releases/tag/v0.27.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: