feat: add robustscaler
Safe-DS/Library pull request #874
Opened 2024-06-28 13:28 UTC by Tarmandan

Closes #650 

### Summary of Changes

Adds a RobustScaler class that works like the StandardScaler but uses median instead of mean and interquartile range instead of standard deviation. If the interquartile range is 0 it will only substract the median from all rows.

For now cannot handle columns containing NaN-values. See Issue #873

2024-06-28 14:04 UTC, lars-reimann requested changes
Just a few nitpicks.

2024-06-28 14:04 UTC, lars-reimann commented on src/safeds/data/tabular/transformation/_robust_scaler.py
> +        This transformer is not modified.
```suggestion
        **Note:** This transformer is not modified.
```

For consistency with more "modern" implementations of transformers. We'll update the others later.

2024-06-28 14:04 UTC, lars-reimann commented on src/safeds/data/tabular/transformation/_robust_scaler.py
> +        The table is not modified.
```suggestion
        **Note:** The given table is not modified.
```

2024-06-28 14:04 UTC, lars-reimann commented on src/safeds/data/tabular/transformation/_robust_scaler.py
> +        The table is not modified.
```suggestion
        **Note:** The given table is not modified.
```

2024-07-01 09:43 UTC, Tarmandan commented on src/safeds/data/tabular/transformation/_robust_scaler.py
> +        # n-tiles = [0.25, 0.125, 0.0675]
This was a holdover from when we were considering more granular handling of high stability. The comment has been removed

2024-07-01 12:44 UTC, lars-reimann approved these changes
Thanks, great work.

2024-07-01 12:45 UTC, merged

2024-07-19 13:01 UTC, lars-reimann commented
:tada: This PR is included in version 0.27.0 :tada:

The release is available on:
- `v0.27.0`
- [GitHub release](https://github.com/Safe-DS/Library/releases/tag/v0.27.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: