789 feat dark mode for plots neu
Safe-DS/Library pull request #911
Opened 2024-07-12 14:33 UTC by saius02

Closes #798 

### Summary of Changes

Implemented Dark Mode for Class Tableplotter and Columnplotter.

2024-07-12 19:33 UTC, lars-reimann requested changes

2024-07-12 19:33 UTC, lars-reimann commented on src/safeds/data/tabular/plotting/_column_plotter.py
> +            The theme for the plot, either "dark" or "light". Default is "light"
```suggestion
            The theme for the plot, either "dark" or "light". Default is "light".
```

2024-07-12 19:33 UTC, lars-reimann commented on tests/safeds/data/tabular/plotting/test_moving_average_plot.py
> +        # (Table({"A": [1, 1, 2, 2, 3, 3, 4, 4, 5, 5], "B": [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]}), "A", "B", 2),
Still needed? If not, please remove.

2024-07-12 19:33 UTC, lars-reimann commented on src/safeds/data/tabular/plotting/_column_plotter.py
>          Create a lag plot for the values in the column.
`theme` parameter should be documented.

2024-07-12 19:33 UTC, lars-reimann commented on src/safeds/data/tabular/plotting/_column_plotter.py
>          Create a box plot for the values in the column. This is only possible for numeric columns.
`theme` parameter should be documented.

2024-07-12 19:33 UTC, lars-reimann commented on src/safeds/data/tabular/plotting/_table_plotter.py
`theme` parameter should be documented.

2024-07-12 19:33 UTC, lars-reimann commented on src/safeds/data/tabular/plotting/_table_plotter.py
>          Plot a correlation heatmap for all numerical columns of this `Table`.
`theme` parameter should be documented.

2024-07-12 19:33 UTC, lars-reimann commented on src/safeds/data/tabular/plotting/_table_plotter.py
>          Plot a histogram for every column.
`theme` parameter should be documented.

2024-07-12 19:33 UTC, lars-reimann commented on src/safeds/data/tabular/plotting/_table_plotter.py
>          Create a line plot for two columns in the table.
`theme` parameter should be documented.

2024-07-12 19:33 UTC, lars-reimann commented on src/safeds/data/tabular/plotting/_table_plotter.py
> +        *,
```suggestion
        *,
        show_confidence_interval: bool = True,
```

Should also be keyword-only, was wrong before.

2024-07-12 19:33 UTC, lars-reimann commented on src/safeds/data/tabular/plotting/_table_plotter.py
`theme` parameter should be documented.

2024-07-12 19:33 UTC, lars-reimann commented on src/safeds/data/tabular/plotting/_table_plotter.py
>          Create a moving average plot for the y column and plot it by the x column in the table.
`theme` parameter should be documented.

2024-07-12 19:33 UTC, lars-reimann commented on src/safeds/data/tabular/plotting/_table_plotter.py
>          #  https://stackoverflow.com/questions/33282368/plotting-a-2d-heatmap
Already done, can be removed.

2024-07-12 19:33 UTC, lars-reimann commented on src/safeds/data/tabular/plotting/_table_plotter.py
> +            import numpy as np
Move the import to the top of the function (line 150).

2024-07-14 11:33 UTC, TobiasPluecker commented
@lars-reimann is there anything to do for us because there is one change requested

2024-07-14 13:01 UTC, lars-reimann requested changes
Should be the last required change.

2024-07-14 13:01 UTC, lars-reimann commented on src/safeds/data/tabular/plotting/_table_plotter.py
> +            The color theme of the plot. Default is "light".
The description for `theme` should be consistent for all functions. The description you used here seems best.

2024-07-14 17:09 UTC, lars-reimann approved these changes
Great work!

2024-07-14 17:09 UTC, merged

2024-07-19 13:01 UTC, lars-reimann commented
:tada: This PR is included in version 0.27.0 :tada:

The release is available on:
- `v0.27.0`
- [GitHub release](https://github.com/Safe-DS/Library/releases/tag/v0.27.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: